---
name: "Code Quality"
on:
  push:
  pull_request:
jobs:
  superlinter:
    name: Super-Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - name: Lint Code
        uses: github/super-linter@45fc0d88288beee4701c62761281edfee85655d7 # v5.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          DEFAULT_BRANCH: "main"
          DISABLE_ERRORS: false
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_ALL_CODEBASE: true
          # VALIDATE_ANSIBLE: false
          # VALIDATE_TERRAFORM_TERRASCAN: true
          # VALIDATE_TERRAFORM_TFLINT: true
          # VALIDATE_MARKDOWN: false
